package com.example.demo.config.seed;

import java.util.List;

/**
 * Seed data for the Actors table and movie–actor links.
 * Each actor has a name and a list of movie IDs. Because IDs are assigned at runtime when
 * movies are persisted, we store 0-based <em>indices</em> into {@link MovieSeedData#MOVIES};
 * the seeder resolves these to actual movie_id values when linking.
 */
public final class ActorSeedData {

    private ActorSeedData() {
    }

    /**
     * Actor name and list of movie indices (0-based positions in MovieSeedData.MOVIES).
     * At seed time these indices are resolved to the corresponding persisted movie IDs.
     */
    public static final List<ActorRow> ACTORS = List.of(
            // Indices 0–4: The Wachowskis
            new ActorRow("Keanu Reeves", List.of(0, 1, 2)),
            new ActorRow("Laurence Fishburne", List.of(0, 1, 2)),
            new ActorRow("Carrie-Anne Moss", List.of(0, 1, 2)),
            new ActorRow("Hugo Weaving", List.of(0, 1, 2, 3, 4)),
            new ActorRow("Natalie Portman", List.of(3)),
            new ActorRow("Stephen Rea", List.of(3)),
            new ActorRow("John Hurt", List.of(3)),
            new ActorRow("Tom Hanks", List.of(4, 30, 44, 47)),
            new ActorRow("Halle Berry", List.of(4)),
            new ActorRow("Jim Broadbent", List.of(4)),
            // 5–10: Christopher Nolan
            new ActorRow("Leonardo DiCaprio", List.of(5, 15, 16, 36)),
            new ActorRow("Joseph Gordon-Levitt", List.of(5)),
            new ActorRow("Elliot Page", List.of(5)),
            new ActorRow("Tom Hardy", List.of(5)),
            new ActorRow("Christian Bale", List.of(6, 9, 25)),
            new ActorRow("Heath Ledger", List.of(6)),
            new ActorRow("Aaron Eckhart", List.of(6)),
            new ActorRow("Michael Caine", List.of(6, 9, 10, 11)),
            new ActorRow("Matthew McConaughey", List.of(7)),
            new ActorRow("Anne Hathaway", List.of(7)),
            new ActorRow("Jessica Chastain", List.of(7)),
            new ActorRow("Guy Pearce", List.of(8)),
            new ActorRow("Joe Pantoliano", List.of(8)),
            new ActorRow("Stephen Tobolowsky", List.of(8)),
            new ActorRow("Hugh Jackman", List.of(9)),
            new ActorRow("Scarlett Johansson", List.of(9)),
            new ActorRow("Cillian Murphy", List.of(10)),
            new ActorRow("Emily Blunt", List.of(10)),
            new ActorRow("Matt Damon", List.of(10)),
            new ActorRow("Robert Downey Jr.", List.of(10, 20, 41)),
            // 11–13: Frank Darabont
            new ActorRow("Tim Robbins", List.of(11)),
            new ActorRow("Morgan Freeman", List.of(11, 39)),
            new ActorRow("Bob Gunton", List.of(11)),
            new ActorRow("William Sadler", List.of(11)),
            new ActorRow("Michael Clarke Duncan", List.of(12)),
            new ActorRow("David Morse", List.of(12)),
            new ActorRow("Bonnie Hunt", List.of(12)),
            new ActorRow("Thomas Jane", List.of(13)),
            new ActorRow("Marcia Gay Harden", List.of(13)),
            new ActorRow("Laurie Holden", List.of(13)),
            new ActorRow("Andre Braugher", List.of(13)),
            // 14–18: Quentin Tarantino
            new ActorRow("John Travolta", List.of(14)),
            new ActorRow("Uma Thurman", List.of(14, 15)),
            new ActorRow("Samuel L. Jackson", List.of(14)),
            new ActorRow("Bruce Willis", List.of(14)),
            new ActorRow("David Carradine", List.of(15)),
            new ActorRow("Daryl Hannah", List.of(15)),
            new ActorRow("Lucy Liu", List.of(15)),
            new ActorRow("Brad Pitt", List.of(16, 17, 36, 38, 39)),
            new ActorRow("Christoph Waltz", List.of(16, 17)),
            new ActorRow("Mélanie Laurent", List.of(16)),
            new ActorRow("Diane Kruger", List.of(16)),
            new ActorRow("Jamie Foxx", List.of(17)),
            new ActorRow("Kerry Washington", List.of(17)),
            new ActorRow("Margot Robbie", List.of(18)),
            new ActorRow("Emile Hirsch", List.of(18)),
            // 19–23: David Fincher
            new ActorRow("Edward Norton", List.of(19)),
            new ActorRow("Helena Bonham Carter", List.of(19)),
            new ActorRow("Meat Loaf", List.of(19)),
            new ActorRow("Kevin Spacey", List.of(20)),
            new ActorRow("Gwyneth Paltrow", List.of(20)),
            new ActorRow("Jake Gyllenhaal", List.of(21)),
            new ActorRow("Mark Ruffalo", List.of(21, 42, 77)),
            new ActorRow("Anthony Edwards", List.of(21)),
            new ActorRow("Jesse Eisenberg", List.of(22)),
            new ActorRow("Andrew Garfield", List.of(22)),
            new ActorRow("Justin Timberlake", List.of(22)),
            new ActorRow("Armie Hammer", List.of(22)),
            new ActorRow("Ben Affleck", List.of(23)),
            new ActorRow("Rosamund Pike", List.of(23)),
            new ActorRow("Neil Patrick Harris", List.of(23)),
            new ActorRow("Tyler Perry", List.of(23)),
            // 24–27: Robert Zemeckis
            new ActorRow("Robin Wright", List.of(24)),
            new ActorRow("Gary Sinise", List.of(24)),
            new ActorRow("Sally Field", List.of(24)),
            new ActorRow("Michael J. Fox", List.of(25, 26)),
            new ActorRow("Christopher Lloyd", List.of(25, 26)),
            new ActorRow("Lea Thompson", List.of(25, 26)),
            new ActorRow("Crispin Glover", List.of(25)),
            new ActorRow("Thomas F. Wilson", List.of(26)),
            new ActorRow("Helen Hunt", List.of(47)),
            new ActorRow("Nick Searcy", List.of(47)),
            new ActorRow("Paul Sanchez", List.of(47)),
            // 28–31: Francis Ford Coppola
            new ActorRow("Marlon Brando", List.of(28, 30)),
            new ActorRow("Al Pacino", List.of(28, 29)),
            new ActorRow("James Caan", List.of(28)),
            new ActorRow("Robert Duvall", List.of(28, 29, 30)),
            new ActorRow("Robert De Niro", List.of(29)),
            new ActorRow("Diane Keaton", List.of(29)),
            new ActorRow("Martin Sheen", List.of(30)),
            new ActorRow("Frederic Forrest", List.of(30)),
            new ActorRow("Gene Hackman", List.of(31)),
            new ActorRow("John Cazale", List.of(31)),
            new ActorRow("Allen Garfield", List.of(31)),
            new ActorRow("Cindy Williams", List.of(31)),
            // 32–36: Peter Jackson
            new ActorRow("Elijah Wood", List.of(32, 33, 34)),
            new ActorRow("Ian McKellen", List.of(32, 33, 34, 35, 36)),
            new ActorRow("Viggo Mortensen", List.of(32, 33, 34)),
            new ActorRow("Sean Astin", List.of(32, 34)),
            new ActorRow("Andy Serkis", List.of(33, 34, 35, 36)),
            new ActorRow("Naomi Watts", List.of(35)),
            new ActorRow("Jack Black", List.of(35)),
            new ActorRow("Adrien Brody", List.of(35)),
            new ActorRow("Martin Freeman", List.of(36)),
            new ActorRow("Richard Armitage", List.of(36)),
            // 37–40: Bong Joon-ho
            new ActorRow("Song Kang-ho", List.of(37, 38, 39, 40)),
            new ActorRow("Lee Sun-kyun", List.of(37)),
            new ActorRow("Cho Yeo-jeong", List.of(37)),
            new ActorRow("Choi Woo-shik", List.of(37)),
            new ActorRow("Kim Sang-kyung", List.of(38)),
            new ActorRow("Kim Roi-ha", List.of(38)),
            new ActorRow("Song Jae-ho", List.of(38)),
            new ActorRow("Byun Hee-bong", List.of(39)),
            new ActorRow("Park Hae-il", List.of(39, 81)),
            new ActorRow("Bae Doona", List.of(39)),
            new ActorRow("Chris Evans", List.of(40)),
            new ActorRow("Tilda Swinton", List.of(40)),
            new ActorRow("Jamie Bell", List.of(40)),
            // 41–45: Hayao Miyazaki (voice actors)
            new ActorRow("Rumi Hiiragi", List.of(41)),
            new ActorRow("Miyu Irino", List.of(41)),
            new ActorRow("Mari Natsuki", List.of(41)),
            new ActorRow("Takashi Naitō", List.of(41)),
            new ActorRow("Noriko Hidaka", List.of(42)),
            new ActorRow("Chika Sakamoto", List.of(42)),
            new ActorRow("Shigesato Itoi", List.of(42)),
            new ActorRow("Sumi Shimamoto", List.of(42)),
            new ActorRow("Yōji Matsuda", List.of(43)),
            new ActorRow("Yuriko Ishida", List.of(43)),
            new ActorRow("Yūko Tanaka", List.of(43)),
            new ActorRow("Kaoru Kobayashi", List.of(43)),
            new ActorRow("Chieko Baishō", List.of(44)),
            new ActorRow("Takuya Kimura", List.of(44)),
            new ActorRow("Tatsuya Gashūin", List.of(44)),
            new ActorRow("Akihiro Miwa", List.of(44)),
            new ActorRow("Hideaki Anno", List.of(45)),
            new ActorRow("Miori Takimoto", List.of(45)),
            new ActorRow("Hidetoshi Nishijima", List.of(45)),
            new ActorRow("Masahiko Nishimura", List.of(45)),
            // 46–48: Jean-Pierre Jeunet
            new ActorRow("Audrey Tautou", List.of(46, 48)),
            new ActorRow("Mathieu Kassovitz", List.of(46)),
            new ActorRow("Rufus", List.of(46)),
            new ActorRow("Lorella Cravotta", List.of(46)),
            new ActorRow("Dominique Pinon", List.of(47, 48)),
            new ActorRow("Marie-Laure Dougnac", List.of(47)),
            new ActorRow("Jean-Claude Dreyfus", List.of(47)),
            new ActorRow("Karin Viard", List.of(47)),
            new ActorRow("Gaspard Ulliel", List.of(48)),
            new ActorRow("Chantal Neuwirth", List.of(48)),
            // 49–51: Fernando Meirelles
            new ActorRow("Alexandre Rodrigues", List.of(49)),
            new ActorRow("Leandro Firmino", List.of(49)),
            new ActorRow("Phellipe Haagensen", List.of(49)),
            new ActorRow("Douglas Silva", List.of(49)),
            new ActorRow("Ralph Fiennes", List.of(50)),
            new ActorRow("Rachel Weisz", List.of(50)),
            new ActorRow("Hubert Koundé", List.of(50)),
            new ActorRow("Danny Huston", List.of(50)),
            new ActorRow("Julianne Moore", List.of(51)),
            new ActorRow("Gael García Bernal", List.of(51)),
            new ActorRow("Danny Glover", List.of(51)),
            // 52–55: Park Chan-wook
            new ActorRow("Choi Min-sik", List.of(52, 53)),
            new ActorRow("Yoo Ji-tae", List.of(52)),
            new ActorRow("Kang Hye-jeong", List.of(52)),
            new ActorRow("Oh Dal-su", List.of(52)),
            new ActorRow("Lee Young-ae", List.of(53)),
            new ActorRow("Tony Barry", List.of(53)),
            new ActorRow("Kwon Yea-young", List.of(53)),
            new ActorRow("Kim Min-hee", List.of(54)),
            new ActorRow("Kim Tae-ri", List.of(54)),
            new ActorRow("Ha Jung-woo", List.of(54)),
            new ActorRow("Cho Jin-woong", List.of(54)),
            new ActorRow("Tang Wei", List.of(55)),
            new ActorRow("Lee Jung-hyun", List.of(55)),
            new ActorRow("Go Kyung-pyo", List.of(55))
    );

    /** Actor name and list of movie indices (0-based in MovieSeedData.MOVIES), resolved to movie_id when seeding. */
    public record ActorRow(String actorName, List<Integer> movieIds) {
    }
}
